### ISSUE TITLE
make historical command text selectable and copyable

### ISSUE THREAD

**Issue by EvilHacker** [muhqu/dterm#10]
I would like to be able to scroll through the command history and copy a command previously entered.
Current the command output can be selected and copied but not the command itself.

**Comment by muhqu** [comment]
Hey @EvilHacker, sry for late reply… you are correct that the command is currently not selectable. But you can use a shortcut to copy the command to the prompt, where it will be selectable.

Use <kbd>⌥⌘←</kbd></big> and <kbd>⌥⌘→</kbd> to cycle throu the history and use <kbd>⌥⌘↑</kbd> to copy the command back to the prompt.

**Comment by muhqu** [comment]
The last command is now also selectable…
