### ISSUE TITLE
Getting the following error lines when using Dterm with Bash version 4.3.46

### ISSUE THREAD

**Issue by petonic** [muhqu/dterm#11]
I think that some of the startup behavior changed in the newer version (4.x) of Bash as opposed to the Mac OS X supplied version.

> bash: cannot set terminal process group (-1): Inappropriate ioctl for device
> bash: no job control in this shell

I am using El Capitan.

Any ideas?  Thanks!

**Comment by petonic** [comment]
Ping...

Is anyone using a Bash version > 4.3 with Dterm successfully?   I'm getting those unseemly error messages above whenever I run a command in Dterm.

Thanks!

**Comment by muhqu** [comment]
@peronic maybe an issue with something in your dot-files? `.bashrc`, `.bash_profile`, `.bash_profile`, ...

Have you tried without them, e.g. by renaming all of them?

**Comment by petonic** [comment]
I haven't renamed all of them, but that's my next step...

What I did do was add a preface into each of the four startup files, and in the case of /etc/profile (since that's the first file executed), I echoed to STDERR.  Could be a buffering issue, I suppose, but really, it looks like the error is happening before the startup files are called.

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
/etc/profile to STDERR
foo
```

Do you happen to have bash v4.3 or newer running on your system?  I'm still using ElCap.

Thanks!

**Comment by petonic** [comment]
Interesting... I renamed the following filed logged in this section:
```
***** Thu Oct 27 12:01:07 PDT 2016: running echo /etc/profile
***** Thu Oct 27 12:01:07 PDT 2016: running echo /etc/bashrc
***** Thu Oct 27 12:01:07 PDT 2016: running echo /Users/petonic/.bash_profile
***** Thu Oct 27 12:01:07 PDT 2016: running echo /Users/petonic/.aliases
```

After I do that, and try to invoke DTERM again, it give me the following (issuing "echo foo" as the command):

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
foo
```

Different error.  It may very well have to do with different Bash 4.X handling of login shells that I'd read about.  OS X default comes with 3.X because of licensing issues, so I installed the newer version.  Maybe my next step is to install the orig OS X Bash back, but I am attached to some of the newer features.

**Comment by petonic** [comment]
Yup.  The older OS X standard /bin/bash version 3.2 works like a champ.  The newer bash version 4.3 makes it exhibit this behavior. 

There were some changes in Gnu's more recent versions, so that explains it.  Has to do with the behavior of login and interactive shells.  Oh well. Back to 3.2 it is for me.  Dterm is quite handy.  Thanks for your effort in maintaining this small but sweet tool.
