### ISSUE TITLE
Colorised output

### ISSUE THREAD

**Issue by anjerodesu** [muhqu/dterm#14]
I've seen many scripts using colorised output depending on the severity of the information. CocoaPods for example uses **red** for errors and **green** for success. Maybe we can incorporate colored outputs to dterm?

**Comment by muhqu** [comment]
Hey @anjerodesu, good news! …DTerm already supports ANSI color! 🎉 

But most cmd-line tools will suppress colored output, as the cmd is run in a none-interactive shell. E.g. stdout/stderr is not connected to a tty.

However, if you force a tool to output colors, DTerm will display them…
![image](https://cloud.githubusercontent.com/assets/26716/21306220/31cb8b1c-c5d0-11e6-9797-4e15324282e5.png)

You can use a bash-function to apply such arguments to the tools you use the most:
```bash
# …in your ~/.bashrc
if [[ "$TERM_PROGRAM" == "DTerm" ]]; then
  pod() {
    "$(which pod)" --ansi "$@"
  }
fi
```

**Comment by muhqu** [comment]
FYI: [Heres the code](https://github.com/muhqu/dterm/blob/4a94e361c0f823dc5e7e452e924723852ed8e2f2/DTRunManager.m#L355) that deals with the ESC sequences. Looks like it lacks support for [256-colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors)…
