### ISSUE TITLE
Compile a 'universal binary' for Apple Silicon chips.

### ISSUE THREAD

**Issue by ershov** [muhqu/dterm#23]
Please make a release for Apple Silicon.

**Comment by muhqu** [comment]
I'm sorry, but I don't use dterm anymore… not sure, but maybe there is a more active fork.

**Comment by ershov** [comment]
A lot of links are pointing here. I can send you a compiled binary or I could add a freshly built release for you in this repo if you want (if I get access).
What do you think?

**Comment by jesse-c** [comment]
There also hasn't been activity for 4 years since 2019. The author hasn't made a commitment to those people linking here. It's clearly not maintained 😬

**Comment by ershov** [comment]
Ok I've done it here: https://github.com/ershov/dterm/releases/tag/1.7.84-universal

@muhqu feel free to re-upload it to your repo as a release if you want an updated binary.

**Comment by muhqu** [comment]
I've now done the same… https://github.com/muhqu/dterm/releases/tag/1.7.86-33877ef
