### ISSUE TITLE
LTS - ?

### ISSUE THREAD

**Issue by aburda** [muhqu/dterm#24]
From prior comments it appears that muhqu is no longer supporting DTERM.  It is one of my favorite things about my Mac setup, I've been using it for 10 years and am about to move over to an M2.  I'm open to supporting the project financially so we can get long term support going.  My company does Qt programming in C++ so Objective C is outside of our area of expertise.  If anybody is interested in collaborating on this let me know.  Presumably somebody who knows how to compile DTERM and can add functionality via objective C.  You can write me via the contact information on my company website, cepuder.com.

**Comment by muhqu** [comment]
Yes, you are right, I'm no longer supporting dterm as I have not used it for several years as I mostly use the integrated terminal of VS Code… 

However, I've just checked out dterm from git and opened it in X Code 15 on my mac M1 running macOS 13 and it's compiling and running out of the box… The command line `./build.sh` script seems broken, but it compiles from XCode UI. 

I'm sorry, but I don't have an active apple developer profile, so I can not provide any signed binaries, but you might want to simply build it yourself.

**Comment by muhqu** [comment]
@aburda I've just published a new release which I've build on my M1 mac… https://github.com/muhqu/dterm/releases/tag/1.7.86-33877ef

Let me know if it is working for you.

**Comment by aburda** [comment]
@muhqu - Excellent many thanks.  I'll give it a try.  I would also like to add some new functionality to DTERM, primarily a history command such that if you press the up arrow it will loop through prior commands, similar to how a terminal would work.  That said, I haven't actually updated my version of DTERM in several years so maybe in this latest release there are new functions.  I'm happy to pay to have the features added and still keep the product open source.

**Comment by aburda** [comment]
I just installed DTERM and it works well on an M2.  Reading through the prior comments, it seems the following would be good to do.

Here is my list of things it seems need to be done.  @muhqu, let me know if you'd be interested or if you are ok with forking if I find somebody to collaborate with.

Create a homebrew formula (Issue #22)
Make historical command text selectable and copyable (Issue #10)
Trusted certificate (Issue #5) - I could probably arrange this on my company account
setup a build server - My company has a TeamCity intance running on AWS if needed 
Setup up/down arrows to move through history in DTERM (my request)
We might also want to change the name of the app since DTERM appears to be taken and makes it difficult to find in a search engine

**Comment by muhqu** [comment]
@aburda just made some additional changes to fix layout issues and while doing that also made the last command selectable/copyable: https://github.com/muhqu/dterm/releases/tag/1.7.91-012c4bc

I appreciate that you want to support the project… but I don't have interest. Feel free to create a fork!

**Comment by aburda** [comment]
@muhqu Many thanks for the updates.  I'll test them shortly, mainly I'm glad that everything works.

**Comment by huyz** [comment]
I do hope someone takes over the fork. This is still a very good secret gem for macOS
