### ISSUE TITLE
Use a trusted certificate for code signage, instead of self-signed

### ISSUE THREAD

**Issue by muhqu** [muhqu/dterm#5]
There are some CAs that provide Code Signing Certificates for open source developers...
- http://stackoverflow.com/questions/1177552/code-signing-certificate-for-open-source-projects/1177748#1177748
- https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

**Comment by ershov** [comment]
"Starting 2016, the Open Source Code Signing certificate is no longer available for free. It is now a paid only service."
