### ISSUE TITLE
Execute in Terminal doesn't work when the Terminal app is active

### ISSUE THREAD

**Issue by iamaziz** [muhqu/dterm#6]
First, thanks a lot for maintaining DTerm. 

After upgrading to the latest release (`1.7.73-4a3bc5c`), Execute in Terminal does not work unless if the Terminal (iTerm) is not opened. Before it was fine, where it opens a new terminal (iTerm) window regardless of if iTerm is running or not. 

My system info:
- El Capitan 10.11
- DTerm: Version 1.7.73-4a3bc5c (1.7.73)
- Default Terminal: iTerm

Problem;
- Nothing happens when I click `cmd-enter`, if iTerm is active.

thanks again.

**Comment by jjarava** [comment]
HI!

This is also happening with DTerm 1.7.69-4b36131 (1.7.69). Are you using the latest iTerm 2 version?

This is happening since I updated to Build 2.9.20160206 of iTerm I think

**Comment by iamaziz** [comment]
Yep, using latest iTerm 2.1.4

**Comment by jjarava** [comment]
When was the 2.1.4 version released? I'm on the beta, and I haven't updated DTerm, but I did update iTerm2 around the time the integration stopped working.

**Comment by iamaziz** [comment]
Check out the awesome v3 beta just came out :) https://www.iterm2.com/version3.html

**Comment by jjarava** [comment]
That's the one I've been running for a while :wink:

iTerm2 `Build 2.9.20160206` is the latest v2 Beta
Unfortunately the "Execute in Terminal" integration is broken as they've changed some things.
I opened a case with their support: https://gitlab.com/gnachman/iterm2/issues/4210 and their response was pretty clear:

>George Nachman @gnachman 2 days ago

>DTerm will need to be updated to use the new applescript syntax. I've reached out to their support folks by email.

Hope this is fixed soon-ish as it's quite a showstopper for me...

**Comment by muhqu** [comment]
@iamaziz, @jjarava sorry for not having noticed this issue for so long… I fixed such an issue back in january, and forgot to push my changes… :-/

**Comment by iamaziz** [comment]
@muhqu great thank you :+1: it now work like a charm.

**Comment by muhqu** [comment]
@iamaziz because I'm already at it… I wanted to adjust the default DTerm window size. how about 70% of other apps window? what do you think?

**Comment by iamaziz** [comment]
It sounds good.. my biggest dreamed wish was that DTerm can maintain the last adjusted window size. For example, when I resize it (with option-drag) to a certain size (say 90%), it will always stay like that even after deactivation :-)

**Comment by iamaziz** [comment]
@muhqu but not sure if that is implementable, overall I think 70% is a great choice.

**Comment by muhqu** [comment]
@iamaziz here you go [1.7.75-4e88dc3](https://github.com/muhqu/dterm/releases/tag/1.7.75-4e88dc3)

Please try it, if you still feel the need to adjust the size submit a feature request and I'll try to make it an option.

**Comment by iamaziz** [comment]
@muhqu it's awesome now :-) thanks! wider and a lot better. 
I guess, that would be sufficient for resizing the window.
