### ISSUE TITLE
Execute in Terminal won't work with DTerm 3 betas

### ISSUE THREAD

**Issue by jjarava** [muhqu/dterm#7]
Hi!

Since updating iTerm2 to the latest beta (`Build 2.9.20160206`, from https://github.com/gnachman/iTerm2/releases/tag/v2.9.20160206 or https://iterm2.com/downloads/beta/iTerm2-2_9_20160206.zip), the `Execute in Terminal` command won't open a new iTerm window as it used to do.

I've reached out to the developers (https://gitlab.com/gnachman/iterm2/issues/4210) and their response is that DTerm needs to be updated:

>George Nachman @gnachman 2 days ago

>DTerm will need to be updated to use the new applescript syntax. I've reached out to their support folks by email.

Looking forward to this issue getting sorted as this is greatly reducing my productivity!

Thanks to both parties!

**Comment by muhqu** [comment]
@jjarava just pushed a new release [1.7.74-4d0c8b3](https://github.com/muhqu/dterm/releases/tag/1.7.74-4d0c8b3) which should fix the issue, can you confirm?

**Comment by jjarava** [comment]
Yes, now it works as previously - I finally can get back to my "workflows"

Thanks!!

**Comment by muhqu** [comment]
@jjarava fyi, I just pushed yet another release wich adjusts DTerm's window size: [1.7.75-4e88dc3](https://github.com/muhqu/dterm/releases/tag/1.7.75-4e88dc3)
