### ISSUE TITLE
iTerm2 v3.0.2 - Displaying Shell Integration/Additional variables before executed command

### ISSUE THREAD

**Issue by JamesValero** [muhqu/dterm#9]
DTerm is showing iTerm2 v3.0.2's Shell Integration variables. How can we prevent it from showing? These don't show in iTerm 3 or Terminal (OS X).

DTerm
![image](https://cloud.githubusercontent.com/assets/10291196/16155186/04e374d8-3463-11e6-9abf-611690a69aa0.png)
![image](https://cloud.githubusercontent.com/assets/10291196/16155514/a632de68-3464-11e6-8d51-0f74e33167d8.png)

iTerm
![image](https://cloud.githubusercontent.com/assets/10291196/16155203/19b1d6b6-3463-11e6-85b1-1570070e8f4d.png)

Terminal
![image](https://cloud.githubusercontent.com/assets/10291196/16155235/4211f24e-3463-11e6-8a31-5ad7669b09e3.png)

**Comment by muhqu** [comment]
I do that by checking for the `ITERM` env var. see [my dot files](https://github.com/muhqu/dotfiles/blob/5d5df29c882032d17c028b65bb9197439107edf9/.bash_profile#L19)

``` shell
if [ -f ~/.iterm2_shell_integration.bash ]; then
	env | grep ITERM >/dev/null && . ~/.iterm2_shell_integration.bash
fi
```

Does that work for you?

**Comment by muhqu** [comment]
@JamesValero did you find time to validate?

**Comment by JamesValero** [comment]
Still showing extra variables. Also tried to restart DTerm.

[image: Inline image 4]

[image: Inline image 6]

[image: Inline image 8]

**Comment by JamesValero** [comment]
Still showing extra variables. Also tried to restart DTerm.

![bash_profile](https://cloud.githubusercontent.com/assets/10291196/16310896/30cce772-3923-11e6-8697-310be5bec0bd.jpg)
![dterm](https://cloud.githubusercontent.com/assets/10291196/16310898/32114484-3923-11e6-96c0-224e3a21da2c.jpg)


Sorry, not sure why images aren't showing in-line above. They are clickable though

**Comment by muhqu** [comment]
@JamesValero from the screenshot of your `~/.bash_profile` it looks like you've not out-commented the original line…

Your original line tested whether the shell integration file exists and then loads it via the `source` command.
```bash
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
```

My version also verifies that there has to be some environment variable with `ITERM` in its name (or value): ` env | grep ITERM >/dev/null && ..`. You can of course also just combine this with your original line…

```bash
test -e "${HOME}/.iterm2_shell_integration.bash" && env | grep ITERM >/dev/null && source "${HOME}/.iterm2_shell_integration.bash"
```

You don't need to restart DTerm for the changes to take affect.

**Comment by muhqu** [comment]
@JamesValero If you still have this problem please let me know.
